
development:
  adapter: postgresql
  encoding: unicode
  database: check_it_off_development
  pool: 5
  username: nicholasbundy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: check_it_off_test
  pool: 5
  username: nicholasbundy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: check_it_off_production
  pool: 5
  username: nicholasbundy
  password:
